apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: aspnet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - image: image
        name: webapp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
