apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebapp
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebapp
  template:
    metadata:
      labels:
        app: simplewebapp
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          name: simplewebapp
          resources:
            requests:
              cpu: 100m
              memory: 300M
            limits:
              cpu: 1
              memory: 800M
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
