apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesprobedemo
  namespace: kubernetesprobedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetesprobedemo
  template:
    metadata:
      labels:
        app: kubernetesprobedemo
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - image: __acrName__.azurecr.io/kubernetesprobedemo:__imageTag__
          name: kubernetesprobedemo
          resources:
            requests:
              cpu: 100m
              memory: 1000M
            limits:
              cpu: 1000m
              memory: 50000M
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
