apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - image: __acrName__.azurecr.io/win-helloworld:__imageTag__
          name: helloworld
          resources:
            requests:
              cpu: 100m
              memory: 300M
            limits:
              cpu: 1
              memory: 800M
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
